spring:
  application:
    name: test-server1
  profiles:
    active: dev
  config:
    import: optional:configserver:http://admin1:1234@localhost:9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://admin1:1234@localhost:8761/eureka

server:
  host: ${server.host}
  port: ${server.port}
